# Site Info
title: dondon
tagline: blog
description: ì˜¤ëŠ˜ë³´ë‹¤ ë” ë‚˜ì€ ë‚´ì¼ì„ ì‚´ì
baseurl: ""
url: https://dondon17.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.2

# About/contact
author:
  name: dondon
  description: Ajou Univ Cyber Security 4th
  contact:
    # linkedin:
    github: https://github.com/dondon17/
    facebook: https://www.facebook.com/25dons/
    instagram: https://www.instagram.com/25dons/
    # twitter:
    # weibo:
    email: mailto:qwerqw889@ajou.ac.kr

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://github.com/dondon17'
  Search:
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

dondon:
  image: /public/img/sky.jpg
  caption: ì—¬í–‰ê°€ê³  ì‹¶ë‹¤ğŸ¤¤

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'dondon17' # leave blank if you don't want disqus

